### ISSUE TITLE
Expose a programmatic API

### ISSUE THREAD

**Issue by perrin4869** [fontello/ttf2eot#4]
We are using this module in https://github.com/agentk/fontfacegen, but unfortunately, without a programmatic API, it is a bit hard to integrate. I think it should be a simple matter of adding a `main` field to `package.json`, as follows:

```json
{
...
main: 'index.js'
...
}
```

Helps solve https://github.com/agentk/fontfacegen/issues/32

**Comment by puzrin** [comment]
Close as declined - path should be resolved properly at your side.
