### ISSUE TITLE
How to set the FamilyName?

### ISSUE THREAD

**Issue by yaoguofeng00000** [fontello/ttf2eot#6]
Due to bug in IE, font FullName MUST begin with FamilyName. For example, if FamilyName is fontello, then FullName should be fontello regular and so on.

How to set it?

**Comment by puzrin** [comment]
This package uses existing data and don't try to change anything. You should have proper ttf souce.

Fontello does necessary workaround https://github.com/fontello/fontello/blob/7.0.0/internal/fontello/font_build/_lib/config.js#L180-L183
