### ISSUE TITLE
ttf2eot hanging on a subsetted TTF file

### ISSUE THREAD

**Issue by 0gust1** [fontello/ttf2eot#7]
config : Windows 7 

font : Roboto TTF font, subsetted with pyftsubset (from fonttools)

I got this bug with node packages using ttf2eot as dependency. 
node version 6.10.0 (I'm currently trying updating node, I'll keep you informed)

```
WORKSPACE\node_modules\microbuffer\index.js:170
    buffer.set(data, offset);
           ^

TypeError: Cannot read property 'length' of undefined
    at Uint8Array.set (native)
    at MicroBuffer.writeBytes (WORKSPACE\node_modules\microbuffer\index.js:170:12)
    at ttf2eot (WORKSPACE\node_modules\ttf2eot\index.js:229:7)
    at Object.<anonymous> (WORKSPACE\node_modules\ttf2eot\ttf2eot.js:58:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by puzrin** [comment]
No idea. Please, provide instructions how to reproduce.

**Comment by 0gust1** [comment]
I just did some dichotomy tests.
* We use the roboto webfont, which we subset for +15 countries in order to have smallest webfont sizes.
* For that (subsetting) we use pyftsubset which outputs subsetted ttf files
* those subsetted TTF files are converted to woff, woff2, eot, svg using nodeJS utilities. Everything is ok but the eot conversion;
 
My learnings so far : 

**I get the problem only with ttf files outputed by pyftsubset. If I run ttf2eot on Roboto original TTF files, I don't get any error.** 

Here the pyftsubset command I launch from node (pretty standard and default).
```
pyftsubset <%=file.path%> --text-file=./subsets/charlists/${folder}.txt --output-file=./dist/hinted/${folder}/<%=file.relative%> --verbose
```
Here the content of a text file used for subsetting (here for French) : 
```

 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~¢£¥¨©«®´¸»ÀÂÆÇÈÉÊËÎÏÔÙÛÜàâæçèéêëîïôùûüÿŒœŸˆ˚˜–—‘’‚“”„…‹›€™
```
The issue is maybe not OS dependent, but more passing the right parameters set to pyftsubset to generate a TTF file that ttf2eot can process.

Do you have any clues on what could be missing in TTF files outputted by pyftsubset (those files seems ok : a browser display them correctly).

**Comment by puzrin** [comment]
i don't know what can be wrong with your files. The only idea is to add `console.log()` everywhere and see what happens.

**Comment by 0gust1** [comment]
Got it ! (with your help) : 
console.log showed that the familyName was empty.

I called pyftsubset with the `--name-IDs='*'` parameter (according to the fonttool documentation) : still no luck.

Some hairs pulled later (and lot of tests using the `ttx` tool of fonttools), I tried with `--name-IDs=*`, and it worked.

Thanks for your hints !

**Comment by puzrin** [comment]
I had no reasons to control all possible bugs. EOT is ancient shit, so i did it to work "somehow, with minimal efforts". With expectation that input TTF is correct.

AFAIK, `familyName` is mandatory, so i'd consider issue as "bad input data". Also, i'd recomment to search for "ttf validator" or "woff validator". Those are not perfect, but can detect some errors.

**Comment by puzrin** [comment]
Closing?

**Comment by 0gust1** [comment]
Of course.
I may drop a comment on fonttools repo
